### PR TITLE
Modified for support MIPSEL

### PR DESCRIPTION
**Pull request by YuanPeir-Chen**
According to issue #183(MIPS not currently supported)
I just updated Turbolua to be able to run also on MIPSEL architecture, it' s work for me on MIPS Box.

Please check out it. Thanks!

### CODE REVIEW

**Comment by kernelsauce** [comment]
Thank you. Will take a closer look tonight/tomorrow.

**Comment by kernelsauce** [comment]
Still not had the time. Be patient :).

**Comment by kernelsauce** [comment]
Looks clean expect for one thing. It does break the Windows builds on Appveyor...

https://ci.appveyor.com/project/kernelsauce/turbo/build/2.0.0-166

Will look at that before accepting PR.

**Comment by YuanPeir-Chen** [comment]
This happens because I modified Makefile in ./deps/http-parser/

if I restore it, it can success for build

Please check it out

https://ci.appveyor.com/project/YuanPeir-Chen/turbo-support-mipsel/build/2.0.0-2

**Comment by kernelsauce** [comment]
Seems fine. Can you include this in the PR?

**Comment by YuanPeir-Chen** [comment]
Yes, it has done!

**Comment by kernelsauce** [comment]
Thank you for the contribution.

**Pull request merged**
